spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/toko_buku_online
    username: tegar
    password: 354313
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    properties:
      hibernate:
        default_schema: public
        enable_lazy_load_no_trans: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
security:
  oauth2:
    client:
      resource-ids: onlinebookstore-resource-id
      id: onlinebookstore-client-id
      client-id: onlinebookstore-secret
      access-token-validity-seconds: 43200
      refresh-token-validity-seconds: 2592000
      authorized-grant-types: password,authorization_code,refresh_token
      scope: read,write
      
server:
  port: 8081